version: "3"
services:
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - VNC_NO_PASSWORD=1
    shm_size: '2gb'
    ports:
      - "6900:5900"
  
  edge:
    image: selenium/node-edge
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - VNC_NO_PASSWORD=1
    shm_size: '2gb'
    ports:
      - "6901:5900"
  
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - VNC_NO_PASSWORD=1
    shm_size: '2gb'
    ports:
      - "6902:5900"
  
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    shm_size: '2gb'
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"